version: '3.7'

services:

  redis:
    image: redis
    container_name: redis
    expose: 
        - 6379

  app:
    container_name: Guaflix-backend
    image: guaflix-backend:dev
    ports: 
        - 5000:5000
    environment: 
        - CHOKIDAR_USEPOLLING=true
    links:
        - redis